### PR TITLE
Remove some asserts, use return Results

### LINKED ISSUE #257: amber fails to compile in release mode.
When I build the release version of amber with gcc 7.3, I get a couple errors:

```
../samples/config_helper_vulkan.cc: In member function ‘void sample::ConfigHelperVulkan::CreateVulkanInstance()’:
../samples/config_helper_vulkan.cc:675:24: error: variable ‘instance_info’ set but not used [-Werror=unused-but-set-variable]
   VkInstanceCreateInfo instance_info = {};
                        ^~~~~~~~~~~~~
../samples/config_helper_vulkan.cc: In member function ‘void sample::ConfigHelperVulkan::CreateVulkanDevice(const VkPhysicalDeviceFeatures&, const std::vector<std::__cxx11::basic_string<char> >&)’:
../samples/config_helper_vulkan.cc:752:22: error: variable ‘info’ set but not used [-Werror=unused-but-set-variable]
   VkDeviceCreateInfo info = {};
                      ^~~~
../samples/config_helper_vulkan.cc: In member function ‘void sample::ConfigHelperVulkan::ChooseVulkanPhysicalDevice(const VkPhysicalDeviceFeatures&, const std::vector<std::__cxx11::basic_string<char> >&)’:
../samples/config_helper_vulkan.cc:714:26: error: ‘count’ is used uninitialized in this function [-Werror=uninitialized]
   physical_devices.resize(count);
   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~

```

This seems to come from [here](https://github.com/google/amber/blob/master/samples/config_helper_vulkan.cc#L683) where real work is in an assert.  That is a problem because that work will not be done in release mode.

There same happens [here](https://github.com/google/amber/blob/master/samples/config_helper_vulkan.cc#L767), and [here](https://github.com/google/amber/blob/master/samples/config_helper_vulkan.cc#L712).

Those are the ones that I found because of compiler errors.  A check should be done for others as well.

### PR DESCRIPTION
**Pull request by dj2**
Fixes #257  where assets were wrapping required calls.

### CODE REVIEW

File: samples/config_helper_vulkan.cc [hunk 1]
```diff
@@ -764,26 +659,46 @@ void ConfigHelperVulkan::CreateVulkanDevice(
...
 
-  CreateVulkanInstance();
-  CreateDebugReportCallback();
-  ChooseVulkanPhysicalDevice(required_vulkan_features, required_extensions);
-  CreateVulkanDevice(required_vulkan_features, required_extensions);
   vkGetDeviceQueue(vulkan_device_, vulkan_queue_family_index_, 0,
                    &vulkan_queue_);
 
-  std::unique_ptr<amber::EngineConfig> cfg_holder =
+  *cfg_holder =
```
Comment (dneto0) [inline samples/config_helper_vulkan.cc]: I would have gone for cfg_holder->reset( the new'd pointer ).

But this is fine.
