### PR TITLE
Vulkan: fix validation errors

### LINKED ISSUE #185: Vulkan: Validation errors after enabling LunarG and Android validation layers

### PR DESCRIPTION
**Pull request by jaebaek**
Fixes #185

### CODE REVIEW

File: src/vulkan/buffer_descriptor.h [hunk 1]
```diff
@@ -67,6 +67,7 @@ class BufferDescriptor : public Descriptor {
   }
 
   std::unique_ptr<Buffer> buffer_;
+  std::vector<std::unique_ptr<Buffer>> not_destroyed_buffers_;
```
Comment (dneto0) [inline src/vulkan/buffer_descriptor.h]: This seems excessive.
Isn't it better to destroy the old buffer when you are resizing it?  That way you don't accumulate more GPU resources over time.

File: src/vulkan/buffer_descriptor.cc [hunk 2]
```diff
@@ -121,6 +121,8 @@ Result BufferDescriptor::CreateOrResizeIfNeeded(
 
     new_buffer->CopyFromBuffer(command, *buffer_);
 
+    not_destroyed_buffers_.push_back(std::move(buffer_));
```
Comment (dneto0) [inline src/vulkan/buffer_descriptor.cc]: Isn't it better to do buffer_->Shutdown() here instead?

Comment (jaebaek) [reply src/vulkan/buffer_descriptor.cc]: The problem is that we must copy the content of `buffer_` to `new_buffer`.
The above line `new_buffer->CopyFromBuffer(command, *buffer_);` record a command for the copy but it did not submit the command yet.
If we destroy `buffer_` here, we lost the information when it actually submit the copy command.

An alternative is plumbing vulkan command buffer here and call submission and reset.

Do u think the alternative is better than keeping those buffers in `not_destroyed_buffers_`?

File: src/vulkan/buffer_descriptor.h (hunk 1 above)
Comment (jaebaek) [reply src/vulkan/buffer_descriptor.h]: See the comment below

File: src/vulkan/buffer_descriptor.cc (hunk 2 above)
Comment (dneto0) [reply src/vulkan/buffer_descriptor.cc]: Ah, right you have to keep the data.  :-)

I still think it's better to destroy the buffer as soon as you can. So I recommend:

   resize is {
     create a new buffer with the bigger size
     copy the data from the old buffer to the new buffer
     destroy the old buffer
     set buffer_ to the newly allocated buffer.
  }

**Comment by jaebaek** [comment]
Blocked on the [discussion](https://github.com/Igalia/vkrunner/issues/46) of the expected behavior when there are multiple updates for a SSBO in VkRunner spec.

File: src/vulkan/buffer_descriptor.cc (hunk 2 above)
Comment (jaebaek) [reply src/vulkan/buffer_descriptor.cc]: As open a bug #200, I will create a PR to replace it with allocation of maximum VkBuffer before starting the execution instead of resizing it.

**Comment by jaebaek** [comment]
I opened two issues related to the discussion in PR #197 #200 
Let me create new PRs for those issues and now this PR is fine?

**Comment by dj2** [comment]
Is this PR still valid or can it be closed now?

File: src/vulkan/buffer_descriptor.cc (hunk 2 above)
Comment (jaebaek) [reply src/vulkan/buffer_descriptor.cc]: We changed the design for this issue. We dropped #200 and will go for #207.

**Comment by jaebaek** [comment]
This PR is still valid except the resizing issue. Why don't we just accept this PR and create a new PR for #207 ? In the new PR, I will remove `BufferDescriptor::not_destroyed_buffers_` because Amber will never recreate buffer for BufferDescriptor anymore.
