### PR TITLE
Vulkan: fix discontinuous descriptor set error

### LINKED ISSUE #158: Error from discontinuous descriptor sets
Amber supports descriptors with consecutive descriptor sets from `[0, N]`, but it does not support discontinuous descriptor sets e.g., `1, 3, 5`.

### PR DESCRIPTION
**Pull request by jaebaek**
Without this commit, Amber supports descriptors with consecutive
descriptor sets from `[0, N]`, but it does not support discontinuous
descriptor sets e.g., `1, 3, 5`. To support discontinuous
descriptor sets, this commit creates empty descriptor set layouts
and puts them on pipeline layout.

Fixes #158

### CODE REVIEW

File: src/vulkan/pipeline.cc [hunk 1]
```diff
@@ -185,10 +221,35 @@ Result Pipeline::CreateDescriptorSets() {
 }
 
 Result Pipeline::CreatePipelineLayout() {
+  // Put all elements of |descriptor_set_layouts_| and
+  // |empty_descriptor_set_layouts_| together. Note that their
+  // order and the order of actually used descriptor sets must
+  // exactly match.
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: I don't understand what this means "their order and the order of actually used descriptor sets must exactly match" ?

File: src/vulkan/pipeline.cc [hunk 2]
```diff
@@ -185,10 +221,35 @@ Result Pipeline::CreateDescriptorSets() {
...
+  std::vector<VkDescriptorSetLayout> layouts;
+  uint32_t desc = 0;
+  size_t empty_descriptor_set_layouts_index = 0;
+  for (size_t i = 0; i < descriptor_set_numbers_.size(); ++i) {
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: Instead of storing to lists, why not just store a vector that you allocate to the max descriptor set value, then fill in the missing ones with empty descriptor sets?

File: src/vulkan/pipeline.cc [hunk 3]
```diff
@@ -113,12 +118,43 @@ Result Pipeline::CreateDescriptorSetLayouts() {
...
-void Pipeline::DestoryDescriptorPools() {
+void Pipeline::DestroyEmptyDescriptorSetLayouts() {
+  for (size_t i = 0; i < empty_descriptor_set_layouts_.size(); ++i) {
+    vkDestroyDescriptorSetLayout(device_, empty_descriptor_set_layouts_[i],
+                                 nullptr);
+  }
+  empty_descriptor_set_layouts_.clear();
+}
+
+Result Pipeline::CreateEmptyDescriptorSetLayouts() {
```
[the remark this answers is not in the document]
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: I removed this method and put both empty and non-empty descriptor set layouts onto `descriptor_set_layouts_`.

File: src/vulkan/pipeline.cc [hunk 4]
```diff
@@ -113,12 +118,43 @@ Result Pipeline::CreateDescriptorSetLayouts() {
...
+  uint32_t desc = 0;
+  for (size_t i = 0; i < descriptor_set_numbers_.size(); ++i) {
```
[the remark this answers is not in the document]
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: I removed `descritpor_set_numbers_`.
I use `std::vector<DescriptorSetLayoutType> descriptor_set_layout_types_` which determines whether each element of `descriptor_set_layouts_` is empty or not.

File: src/vulkan/pipeline.cc (hunk 1 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: I removed this code to put both empty and non-empty ones together.

File: src/vulkan/pipeline.cc (hunk 2 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: Updated. I put all together into `descriptor_set_layouts_`.

File: src/vulkan/pipeline.cc [hunk 5]
```diff
@@ -312,11 +346,20 @@ Result Pipeline::SendDescriptorDataToDeviceIfNeeded() {
...
-  vkCmdBindDescriptorSets(command_->GetCommandBuffer(),
-                          IsGraphics() ? VK_PIPELINE_BIND_POINT_GRAPHICS
-                                       : VK_PIPELINE_BIND_POINT_COMPUTE,
-                          pipeline_layout_, 0, descriptor_sets_.size(),
-                          descriptor_sets_.data(), 0, nullptr);
+  for (size_t desc = 0, non_empty_desc = 0;
+       desc < descriptor_set_layout_types_.size() &&
+       non_empty_desc < descriptor_sets_.size();
+       ++desc) {
+    if (descriptor_set_layout_types_[desc] ==
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: if (descriptor_set_layout_types_[desc] != DescriptorSetLayotuType::kNonEmpty)
  continue;

File: src/vulkan/pipeline.cc [hunk 6]
```diff
@@ -166,19 +192,25 @@ Result Pipeline::CreateDescriptorPools() {
...
-    desc_set_info.pSetLayouts = &descriptor_set_layouts_[i];
-
-    VkDescriptorSet desc_set = VK_NULL_HANDLE;
-    if (vkAllocateDescriptorSets(device_, &desc_set_info, &desc_set) !=
-        VK_SUCCESS) {
-      return Result("Vulkan::Calling vkAllocateDescriptorSets Fail");
+  for (size_t desc = 0, pool = 0; desc < descriptor_set_layout_types_.size() &&
+                                  pool < descriptor_pools_.size();
+       ++desc) {
+    if (descriptor_set_layout_types_[desc] ==
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: if (descriptor_set_layotu_types_[desc] != DescriptorSetLayoutType::kNonEmpty)
  continue;

File: src/vulkan/pipeline.cc (hunk 5 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: done

File: src/vulkan/pipeline.cc (hunk 6 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: done

File: src/vulkan/pipeline.cc [hunk 7]
```diff
@@ -65,87 +65,107 @@ void Pipeline::Shutdown() {
   if (r.IsSuccess())
     command_->SubmitAndReset(fence_timeout_ms_);
 
-  DestoryDescriptorPools();
-  DestoryDescriptorSetLayouts();
+  for (size_t desc = 0; desc < descriptor_sets_.size(); ++desc) {
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: Let's change desc to i. Naming it desc makes me think it's the descriptor, not the index.

File: src/vulkan/pipeline.cc [hunk 8]
```diff
@@ -65,87 +65,107 @@ void Pipeline::Shutdown() {
...
   size_t i = 0;
+  uint32_t next_desc = 0;
   while (i < descriptors_.size()) {
     std::vector<VkDescriptorSetLayoutBinding> bindings;
-    for (const uint32_t current_desc = descriptors_[i]->GetDescriptorSet();
-         i < descriptors_.size() &&
-         current_desc == descriptors_[i]->GetDescriptorSet();
-         ++i) {
+    const uint32_t current_desc = descriptors_[i]->GetDescriptorSet();
+    while (i < descriptors_.size() &&
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: What is the relation between descriptors_ and descriptor_sets_? Is it 1:1?

File: src/vulkan/pipeline.cc [hunk 9]
```diff
@@ -159,36 +179,57 @@ Result Pipeline::CreateDescriptorPools() {
         VK_SUCCESS) {
       return Result("Vulkan::Calling vkCreateDescriptorPool Fail");
     }
-    descriptor_pools_.push_back(desc_pool);
+
+    if (static_cast<uint32_t>(descriptor_sets_.size()) <= current_desc) {
+      return Result(
+          "Pipeline::CreateDescriptorPools more actually used descriptor sets "
+          "than descriptor set layouts");
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: "Pipeline::CreateDescriptorPools: More descriptor sets requested then descriptor set layouts provided"

File: src/vulkan/pipeline.cc [hunk 10]
```diff
@@ -159,36 +179,57 @@ Result Pipeline::CreateDescriptorPools() {
...
+    }
+
+    if (descriptor_sets_[current_desc].empty) {
+      return Result(
+          "Pipeline::CreateDescriptorPools actually used descriptor set has "
+          "empty descriptor set layout");
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: "Pipeline::CreateDescriptorPools: Used a descriptor set with an empty layout"

File: src/vulkan/pipeline.cc [hunk 11]
```diff
@@ -159,36 +179,57 @@ Result Pipeline::CreateDescriptorPools() {
...
+
+    descriptor_sets_[current_desc].pool = desc_pool;
   }
 
   return {};
 }
 
 Result Pipeline::CreateDescriptorSets() {
-  for (size_t i = 0; i < descriptor_set_layouts_.size(); ++i) {
+  for (size_t desc = 0; desc < descriptor_sets_.size(); ++desc) {
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: Let's use i instead of desc.

File: src/vulkan/pipeline.cc [hunk 12]
```diff
@@ -220,14 +260,28 @@ Result Pipeline::CreateVkDescriptorRelatedObjectsIfNeeded() {
...
     for (const uint32_t current_desc = descriptors_[i]->GetDescriptorSet();
          i < descriptors_.size() &&
          current_desc == descriptors_[i]->GetDescriptorSet();
          ++i) {
-      Result r =
-          descriptors_[i]->UpdateDescriptorSetIfNeeded(descriptor_sets_[j]);
+      if (static_cast<uint32_t>(descriptor_sets_.size()) <= current_desc) {
+        return Result(
+            "Pipeline::UpdateDescriptorSetsIfNeeded more actually used "
+            "descriptor sets than descriptor set layouts");
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: same change as above

File: src/vulkan/pipeline.cc [hunk 13]
```diff
@@ -220,14 +260,28 @@ Result Pipeline::CreateVkDescriptorRelatedObjectsIfNeeded() {
...
+      }
+
+      if (descriptor_sets_[current_desc].empty) {
+        return Result(
+            "Pipeline::UpdateDescriptorSetsIfNeeded actually used descriptor "
+            "set has empty descriptor set layout");
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: same change as above.

File: src/vulkan/pipeline.h [hunk 14]
```diff
@@ -83,29 +83,34 @@ class Pipeline {
...
-  std::vector<VkDescriptorSetLayout> descriptor_set_layouts_;
-  std::vector<VkDescriptorPool> descriptor_pools_;
-  std::vector<VkDescriptorSet> descriptor_sets_;
-
   VkDevice device_ = VK_NULL_HANDLE;
   VkPhysicalDeviceMemoryProperties memory_properties_;
   std::unique_ptr<CommandBuffer> command_;
 
  private:
+  struct DescriptorSet {
```
Comment (dj2) [inline src/vulkan/pipeline.h]: Should this just be part of the Descriptor object? It seems like they're always used together?

File: src/vulkan/pipeline.cc (hunk 7 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: done

File: src/vulkan/pipeline.cc (hunk 8 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: N:1
Each element of `descriptor_sets_` can be matched to one or more elements of `descriptors_`

File: src/vulkan/pipeline.cc (hunk 9 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: done
I used "than" not "then"

File: src/vulkan/pipeline.cc (hunk 10 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: done

File: src/vulkan/pipeline.cc (hunk 11 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: done

File: src/vulkan/pipeline.cc (hunk 12 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: done

File: src/vulkan/pipeline.cc (hunk 13 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: done

File: src/vulkan/pipeline.h (hunk 14 above)
Comment (jaebaek) [reply src/vulkan/pipeline.h]: Hmm .. I don't think so.

- `DescriptorSet` is not 1:1 matched with `Descriptor`. `DescriptorSet` has one or more `Descriptor`.
- `Descriptor` does not use `DescriptorSet` inside. It is only used by `Pipeline`.

Comment (dj2) [reply src/vulkan/pipeline.h]: So, how are they related? Is a DescriptorSet required to make a Descriptor? One DescriptorSet can make multiple Descriptors but the DescriptorSets have to be contiguous? Can we change the DescriptorSets struct to have a vector<Descriptor> in it which is all the descriptors for a given DescriptorSet?

File: src/vulkan/pipeline.cc [hunk 15]
```diff
@@ -65,75 +65,60 @@ void Pipeline::Shutdown() {
...
-
 Result Pipeline::CreateDescriptorSetLayouts() {
-  std::sort(descriptors_.begin(), descriptors_.end());
+  for (auto& info : descriptor_set_info_) {
+    VkDescriptorSetLayoutCreateInfo desc_info = {};
+    desc_info.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
 
-  size_t i = 0;
-  while (i < descriptors_.size()) {
+    // If two descriptor sets are discontinuous, we must put empty
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: I think this comment is out of date. Something like:

If there are no descriptors for this descriptor_set we only need to create the layout and
there will be no bindings.

File: src/vulkan/pipeline.cc [hunk 16]
```diff
@@ -299,11 +307,16 @@ Result Pipeline::SendDescriptorDataToDeviceIfNeeded() {
   if (!r.IsSuccess())
     return r;
 
-  for (const auto& desc : descriptors_) {
-    r = desc->CreateOrResizeIfNeeded(command_->GetCommandBuffer(),
-                                     memory_properties_);
-    if (!r.IsSuccess())
-      return r;
+  for (auto& info : descriptor_set_info_) {
+    if (info.empty)
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: This check isn't needed because the for() below won't do anything if it's empty

File: src/vulkan/pipeline.cc [hunk 17]
```diff
@@ -281,15 +284,20 @@ Result Pipeline::AddDescriptor(const BufferCommand* buffer_command) {
...
-  if (descriptors_.size() == 0)
-    return {};
-
   bool data_send_needed = false;
-  for (const auto& desc : descriptors_) {
-    if (desc->HasDataNotSent()) {
-      data_send_needed = true;
-      break;
+  for (auto& info : descriptor_set_info_) {
+    if (info.empty)
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: Check not needed.

File: src/vulkan/pipeline.cc [hunk 18]
```diff
@@ -216,49 +206,62 @@ Result Pipeline::CreateVkDescriptorRelatedObjectsIfNeeded() {
...
-  for (size_t i = 0, j = 0;
-       i < descriptors_.size() && j < descriptor_sets_.size(); ++j) {
-    for (const uint32_t current_desc = descriptors_[i]->GetDescriptorSet();
-         i < descriptors_.size() &&
-         current_desc == descriptors_[i]->GetDescriptorSet();
-         ++i) {
-      Result r =
-          descriptors_[i]->UpdateDescriptorSetIfNeeded(descriptor_sets_[j]);
+  for (auto& info : descriptor_set_info_) {
+    if (info.empty)
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: Check not needed

File: src/vulkan/pipeline.cc [hunk 19]
```diff
@@ -324,19 +337,28 @@ Result Pipeline::SendDescriptorDataToDeviceIfNeeded() {
   if (!r.IsSuccess())
     return r;
 
-  for (const auto& desc : descriptors_) {
-    desc->UpdateResourceIfNeeded(command_->GetCommandBuffer());
+  for (auto& info : descriptor_set_info_) {
+    if (info.empty)
```
Comment (dj2) [inline src/vulkan/pipeline.cc]: Check not needed

File: src/vulkan/pipeline.cc (hunk 15 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: done

File: src/vulkan/pipeline.cc (hunk 18 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: removed

File: src/vulkan/pipeline.cc (hunk 17 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: removed

File: src/vulkan/pipeline.cc (hunk 16 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: removed

File: src/vulkan/pipeline.cc (hunk 19 above)
Comment (jaebaek) [reply src/vulkan/pipeline.cc]: removed

File: src/vulkan/pipeline.cc [hunk 20]
```diff
@@ -65,75 +65,60 @@ void Pipeline::Shutdown() {
...
-      bindings.back().binding = descriptors_[i]->GetBinding();
-      bindings.back().descriptorType =
-          ToVkDescriptorType(descriptors_[i]->GetType());
-      bindings.back().descriptorCount = 1;
-      // TODO(jaebaek): Amber script must contain which stages use each
-      //                descriptor. Set .stageFlags attribute based on it.
-      bindings.back().stageFlags = VK_SHADER_STAGE_ALL;
-      // TODO(jaebaek): Properly set .pImmutableSamplers attribute.
-    }
+    if (!info.empty) {
```
Comment (jaebaek) [inline src/vulkan/pipeline.cc]: I also removed check here.
